import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { roboto } from "./fonts"
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={roboto.style}>
        <div className="fixed top-0 left-0 right-0 z-40">
          <Navbar/>
        </div>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
